### ISSUE TITLE
PHP Warning:  Undefined property: stdClass::$activitycompletion

### ISSUE THREAD

**Issue by acquaalta** [Annoto/moodle-local_annoto#136]
Hi,
Moodle version: 4.3.3
Plugin version: 5.2.0 (2024043000)

It seems that the CRON of the Moodle server sends these messages sometimes:
PHP Warning:  Undefined property: stdClass::$activitycompletion in /usr/share/moodle/local/annoto/classes/task/completion.php on line 62 PHP Warning:  Undefined property: stdClass::$activitycompletion in /usr/share/moodle/local/annoto/classes/task/completion.

Could you please fix this?

Thanks :-)

**Comment by genadis** [comment]
we are not able to reproduce.
please update to the latest V5.3.0.
If the issue still persists, please write a comment and I'll reopen.
