### ISSUE TITLE
local_annoto_external::get_jsparams should implement a capability check

### ISSUE THREAD

**Issue by danmarsden** [Annoto/moodle-local_annoto#21]
Typically an externallib class will implement some permission checking to see if the user can view the course / access the data before doing anything. I think you should probably be adding a new capability that you give to students/teachers and checking that before getting the data.

**Comment by genadis** [comment]
users are treated as viewers with read only capability unless they have a token.
All the permissions of teacher/student (more then the default viewer) etc are checked when generating the token at:
[local_annoto_get_user_token](https://github.com/Annoto/moodle-local_annoto/blob/master/lib.php#L59)
without this token (empty), Annoto system will treat the user as the default viewer. How to handle those viewers is configured at the system level outside the scope of the plugin.
